default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: register_product_development

test:
  <<: *default
  database: register_product_test

production:
  <<: *default
  database: register_product_production
  username: register_product
  password: <%= ENV["REGISTER_PRODUCT_DATABASE_PASSWORD"] %>
